### ISSUE TITLE
App uses renderToString, preventing streaming

### ISSUE THREAD

**Issue by jamesarosen** [tw-in-js/example-remix#1]
The app [uses `react-dom/server`'s `renderToString`](https://github.com/tw-in-js/example-remix/blob/f32c000de834fa9ee8836e88ae88fb0c7b6346af/app/entry.server.tsx#L15-L17), which causes Remix to render the whole page to a string server-side.

The [example in remix-run/examples](https://github.com/remix-run/examples/tree/main/twind) [uses `renderToPipeableStream`](https://github.com/remix-run/examples/blob/fb7fee55fd37f1595b1513e6d24279a070c273bc/twind/app/entry.server.tsx#L42-L43).

As far as I can tell, `inline` itself consumes the input buffer (or string) so it can extract styles and write the `<style>` tag.

Is one approach preferred over the other? Why?

**Comment by itsMapleLeaf** [comment]
Sorry, this repo is actually a bit outdated and hasn't been touched since its creation

[The "more official" example exists here](https://github.com/tw-in-js/twind/tree/main/examples/with-remix), but it appears to have the same issue. I would raise this issue over at the official twind repo. I'll probably archive this
